# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15c071b1ae99f9a6f458770b5e844681d6ba29ba124abe4178ae647af5ead216a8ea5348b9c433be8c8d85d7cd1bfb94f29ed8f6ad2c1cbbc9f7d625fea46bd1

test:
  secret_key_base: 00ddea2f89851c910ea6c39fbf76cd36261d346ad021018cdd7c927acc75fd909aff6261c906360b7887db62f7a6b22bc05ac59f6f2c0fc8d030d7fba6bd2d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
